package com.jack.pinpoint.jumper;

import org.apache.thrift.TException;
import org.apache.thrift.TProcessor;
import org.apache.thrift.protocol.TJSONProtocol;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.protocol.TSimpleJSONProtocol;
import org.apache.thrift.transport.TIOStreamTransport;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;

/**
 * Get the json string generated by thrift client
 * Created by jack on 17-4-19.
 */
public class DummyTalkClinet {
    public static void generateJson() {
        InputStream in=new ByteArrayInputStream(new String("abc").getBytes());;
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        TIOStreamTransport transport = new TIOStreamTransport(in, out);
        TProtocol inProtocol = new TSimpleJSONProtocol(transport);
        TProtocol outProtocol = new TSimpleJSONProtocol(transport);
        TalkService.Client client = new TalkService.Client(outProtocol);
        try {
            client.talk("jack");
        } catch (TException e) {
            System.out.println("got "+e);
            e.printStackTrace();
        }
        String result=out.toString();
        System.out.println("result string="+result);
    }

    public static void dummyServer() {
        TProcessor processor=new TalkService.Processor(new TalkServiceImpl());

        InputStream in=new ByteArrayInputStream(new String("[1,\"talk\",1,1,{\"1\":{\"str\":\"jack\"}}]").getBytes());
        ByteArrayOutputStream out = new ByteArrayOutputStream();

//        try {
//            byte[] b=new byte[1];
//            in.read(b);
//            System.out.println(new String(b));
//        } catch (IOException e) {
//            System.out.println("got exception"+e);
//            e.printStackTrace();
//        }


        TIOStreamTransport e = new TIOStreamTransport(in, out);
        TProtocol inProtocol = new TJSONProtocol(e);
        TProtocol outProtocol = new TJSONProtocol(e);

        try {
            processor.process(inProtocol, outProtocol);
        } catch (TException e1) {
        }

        String str = out.toString();
    }

    public static class TalkServiceImpl implements TalkService.Iface {

        public String talk(String name) throws TException {
            System.out.println("================================================         TalkServiceImpl.talk() called");
            return "talk with echo is cool";
        }
    }

    public static void main(String[] args) {
        dummyServer();
    }
}
